name: exam api data pipeline

on:
  schedule:
    - cron: "*/5 * * * *"  # 매일 오후 3시 (UTC 기준 6시)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: api data 갱신
        run: |
          pip install requests
          python api.py

      - name: 변경 사항 커밋 및 푸시
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "test.json 업데이트" || echo "No changes to commit"
          git push